/* My application simulates an online store. The program begins
by displaying a list of products and their prices inside a Combobox. The program
allows the user to select an item from the Combobox and enter the quantity of products
they wish to purchase in the given text box. The program then prints out a recipt with
the price of the products purchased as well as the total price for all items purchased.
The user can keep choosing more products and quantities for as long as the user wishes.
When they are done they can click on the "clear" button on the top right to restart by clearing
the screen and all previous assigned values.*/

// I've imported the neccessary packages from the java libary
import java.text.DecimalFormat;
import javax.swing.JFrame;

// @author 21422705 Abas Abdi
public class Store extends javax.swing.JFrame {

    /* This creates a new form called Store were i set the size,
 the close operation, title, & called the initComponents method. */
    public Store() {
        this.setSize(200, 100);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("ONLINE STORE");

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("STORE ITEMS");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("STORE ITEMS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My Post (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 10, 320, 60));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apples (£0.50)", "Oranges (£0.60)", "Mangoes (£1.25)", "Corn (£0.38)", "Peas (£0.64)", "Tomatoes (£0.33)", "Pears (£0.40)", "Carrots (£1.26)", "Watermelons (£1.12)", "Pineapples (£1.70)" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 139, 33));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 314, 40));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 320, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/basket (3).png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 70, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlb.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 300, 60));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 286, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tp.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 60, 50));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back3.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* I declared & initialised a float called "Amount" outside of the button action event
     so that the value doesn't return back to zero whenever the button is clicked. */
    float Amount = 0f;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /* I declared and initialised my arrays called product and prive here but it didn't really matter
    if they were within or outside the button action event. */
        String[] product = {"Apples", "Oranges", "Mangoes", "Corn", "Peas", "Tomatoes", "Pears", "Carrots", "Watermelons", "Pineapples"};
        float[] prices = {0.50f, 0.60f, 1.25f, 0.38f, 0.64f, 0.33f, 0.40f, 1.26f, 1.12f, 1.70f};
        /* I specfically chose to declare and initialise the arry called quantity inside the button action event
    because i wanted the values to return to zero whener the button was clicked */
        int[] quantity = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
        // I've declared an object called f and initalised it with the DecimalFormat i wanted.
        DecimalFormat f = new DecimalFormat("0.00");

        /* I used an if statement to store the quantity the user entered in a specific part of the quantity array
       depending on which item in the ComboBox the user selected.*/
        if (jComboBox1.getSelectedItem().equals("Apples (£0.50)")) {
            quantity[0] = Integer.parseInt(jTextField1.getText());
        } else if (jComboBox1.getSelectedItem().equals("Oranges (£0.60)")) {
            quantity[1] = Integer.parseInt(jTextField1.getText());
        } else if (jComboBox1.getSelectedItem().equals("Mangoes (£1.25)")) {
            quantity[2] = Integer.parseInt(jTextField1.getText());
        } else if (jComboBox1.getSelectedItem().equals("Corn (£0.38)")) {
            quantity[3] = Integer.parseInt(jTextField1.getText());
        } else if (jComboBox1.getSelectedItem().equals("Peas (£0.64)")) {
            quantity[4] = Integer.parseInt(jTextField1.getText());
        } else if (jComboBox1.getSelectedItem().equals("Tomatoes (£0.33)")) {
            quantity[5] = Integer.parseInt(jTextField1.getText());
        } else if (jComboBox1.getSelectedItem().equals("Pears (£0.40)")) {
            quantity[6] = Integer.parseInt(jTextField1.getText());
        } else if (jComboBox1.getSelectedItem().equals("Carrots (£1.26)")) {
            quantity[7] = Integer.parseInt(jTextField1.getText());
        } else if (jComboBox1.getSelectedItem().equals("Watermelons (£1.12)")) {
            quantity[8] = Integer.parseInt(jTextField1.getText());
        } else if (jComboBox1.getSelectedItem().equals("Pineapples (£1.70)")) {
            quantity[9] = Integer.parseInt(jTextField1.getText());
        }

        /* I then used a for loop to go through the quantity and price indexes and multiply the values they contain,
        adding them together and putting the sum in the Amount variable.*/
        for (int i = 0; i < quantity.length; i++) {
            /* I put an if statement within the loop so that only products the user chose are singled out to be printed
            in the Receipt that i would like the user to recieve. */
            if (quantity[i] > 0) {
                jTextArea1.append("RECEIPT:\nYou've purchased " + quantity[i] + " " + product[i] + " for £" + String.valueOf(f.format(quantity[i] * prices[i])) + "\n");

            }
            Amount += (quantity[i] * prices[i]);
        }

        /* I used ".append" instead of ".setText" so that the values in the Text Area aren't cleared every
        time the user clicks on the shopping cart button*/
        jTextArea1.append("Total price: £" + f.format(Amount) + "\n\n");


    }//GEN-LAST:event_jButton1ActionPerformed


    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // When this button is clicked I'm clearing the screen by setting the TextAra and TextField to ""
        jTextArea1.setText("");
        jTextField1.setText("");
        // I'm also resetting the value of Amount back to 0 so that it shows the total for new values.
        Amount = 0f;
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            new Store().setVisible(true);
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
